name: VIC Update

on:
  push:
    branches:
      - master
  schedule:
    # - cron: '0-59/5 * * * *' # Every 5 minutes
    - cron: '15 22 * * *' # Daily at 22:30 UTC (9:15am AEDT)

defaults:
  run:
    shell: bash


jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: SVG
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pytz tableauhyperapi==0.0.11355 pantab requests pandas lxml

      - name: Run
        run: |
          python victoria.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: VIC Automatic Update
